baseURL = 'https://icept.github.io/short-street-cook-book/'
languageCode = 'en-au'
title = 'Short Street Cook Book'
theme = 'hugo-book'
disableKinds = ['taxonomy', 'term']

[params]
  BookTheme = 'auto'
  BookSearch = true
  BookCollapsibleMenu = true
  BookToC = false
  BookRepo = 'https://github.com/icept/short-street-cook-book'
