baseURL = 'https://icept.github.io/short-street-cook-book/'
title = 'Short Street Cook Book'
theme = 'hugo-book'
canonifyURLs = true
disableKinds = ['taxonomy', 'term']

[languages.en]
  locale = 'en-AU'

[params]
  BookTheme = 'auto'
  BookSearch = true
  BookCollapsibleMenu = true
  BookToC = false
  BookSection = '/'
  BookRepo = 'https://github.com/icept/short-street-cook-book'
